### ISSUE TITLE
Rivendel 3.0

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell-install#2]
Is rivendell-install going to be updated for Rivendel 3.0 or is it going away?

**Comment by ElvishArtisan** [comment]
On Oct 21, 2018, at 02:39, Deltec Enterprises <notifications@github.com> wrote:

> Is rivendell-install going to be updated for Rivendel 3.0 or is it going away?

There’ll be an update, along with a new repo for 3.x betas. Hopefully tomorrow. Once we have that working smoothly, then we'll call it ‘beta’ and announce to the community. Then the real fun begins…  :)

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|
